model:
  path: model_ck
  device: cuda
  torch_dtype: bfloat16
  attn_implementation: flash_attention_2

inference:
  fps: 1
  max_frames: 160
  modal: video
  max_new_tokens: 180
  do_sample: False
  merge_size: 2
  timeout: 300